[en]
label = "English"
locale = "en-us"
contentDir = "content/en"
title = "Hugo Theme Starter"
weight = 1

[en.params]
flag_image = "english"
flag_alt = "English"

[de]
label = "Deutsch"
locale = "de-de"
contentDir = "content/de"
title = "Hugo Theme Starter"
weight = 2

[de.params]
flag_image = "german"
flag_alt = "Deutsch"
